name: Build then Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Build
      run: cargo build --release

    - name: Upload sync.exe
      uses: actions/upload-artifact@v2
      with:
        name: sync.exe
        path: target/release/sync.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download sync.exe
      uses: actions/download-artifact@v2
      with:
        name: sync.exe


    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: sync.exe
        tag_name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}